{% set name = "pyobjc-framework-CoreServices" %}
{% set version = "12.1" %}
{% set pypi_name = name|replace("-", "_")|lower %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ pypi_name[0] }}/{{ name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: fc6a9f18fc6da64c166fe95f2defeb7ac8a9836b3b03bb6a891d36035260dbaa

build:
  number: 0
  skip: true  # [not osx or py<10]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - python
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - pyobjc-core >={{ version }}
    - pyobjc-framework-fsevents >={{ version }}
    - pyobjc-framework-cocoa >={{ version }}

test:
  imports:
    - CoreServices
    - CoreServices.CarbonCore
    - CoreServices.DictionaryServices
    - CoreServices.LaunchServices
    - CoreServices.Metadata
    - CoreServices.SearchKit
  requires:
    - pip
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"

about:
  home: https://github.com/ronaldoussoren/pyobjc
  summary: Wrappers for the “CoreServices” framework on macOS.
  description: |
    The PyObjC project aims to provide a bridge between the Python and
    Objective-C programming languages on macOS. The bridge is intended to be
    fully bidirectional, allowing the Python programmer to take full advantage
    of the power provided by various Objective-C based toolkits and the
    Objective-C programmer transparent access to Python based functionality.
  license: MIT
  license_family: MIT
  license_file: License.txt
  doc_url: https://pyobjc.readthedocs.io/
  dev_url: https://github.com/ronaldoussoren/pyobjc

extra:
  recipe-maintainers:
    - andfoy
    - ccordoba12
    - dalthviz
    - steff456
